### ISSUE TITLE
bug relate to plist file size

### ISSUE THREAD

**Issue by cguo2013** [ic005k/PlistEDPlus#14]
edit same plist file in this tool, compare the file size with other plist editor in Windows (proper tree) and MAC OS (OCC, etc), I can find that file size are different, the one edit in this tool is bigger. 
I doubt it is because the software try to save all the space characters inside the text file?

**Comment by cguo2013** [comment]
note I only use win64 version so far

**Comment by ic005k** [comment]
Yes, the reason for the file size increase is that PlistEDPlus uses spaces for indentation instead of TAB for indentation.
For the reason why spaces are used for indentation, please see here：
https://www.insanelymac.com/forum/topic/344752-open-source-cross-platform-opencore-auxiliary-tools/page/6/?tab=comments#comment-2753995

**Comment by ic005k** [comment]
In other words, PlistEDPlus is more adaptable to various editing environments, which other similar plist editors currently do not have.

**Comment by cguo2013** [comment]
got it thanks, would be good to add an enable/disable option to such extra feature, cause it will result in file size changes.
